name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [11, 17, 21]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.version }}
        distribution: temurin
    - run: test/test.sh
